spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8090/
          predicates:
            - Path=/clients/**
        - id: r2
          uri: http://localhost:8090/
          predicates:
            - Path=/client/**
